//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Firma.Intranet.ViewResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Firma.Intranet.ViewResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresy.
        /// </summary>
        public static string Adresy {
            get {
                return ResourceManager.GetString("Adresy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string Cena {
            get {
                return ResourceManager.GetString("Cena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceny.
        /// </summary>
        public static string Ceny {
            get {
                return ResourceManager.GetString("Ceny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy napewno usunąć poniższe dane?.
        /// </summary>
        public static string CzyNapewno1 {
            get {
                return ResourceManager.GetString("CzyNapewno1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy element.
        /// </summary>
        public static string DodajNowyEl {
            get {
                return ResourceManager.GetString("DodajNowyEl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja.
        /// </summary>
        public static string Edycja {
            get {
                return ResourceManager.GetString("Edycja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahenci.
        /// </summary>
        public static string Kontrahenci {
            get {
                return ResourceManager.GetString("Kontrahenci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrahent.
        /// </summary>
        public static string Kontrahent {
            get {
                return ResourceManager.GetString("Kontrahent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monter.
        /// </summary>
        public static string Monter {
            get {
                return ResourceManager.GetString("Monter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monterzy.
        /// </summary>
        public static string Monterzy {
            get {
                return ResourceManager.GetString("Monterzy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót do listy.
        /// </summary>
        public static string PowrotDoListy {
            get {
                return ResourceManager.GetString("PowrotDoListy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozycja zamówienia zakupu.
        /// </summary>
        public static string PozycjaZZ {
            get {
                return ResourceManager.GetString("PozycjaZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozycje zamówienia zakupu.
        /// </summary>
        public static string PozycjeZZ {
            get {
                return ResourceManager.GetString("PozycjeZZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        public static string Produkt {
            get {
                return ResourceManager.GetString("Produkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt uboczny.
        /// </summary>
        public static string ProduktUboczny {
            get {
                return ResourceManager.GetString("ProduktUboczny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkty.
        /// </summary>
        public static string Produkty {
            get {
                return ResourceManager.GetString("Produkty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkty uboczne.
        /// </summary>
        public static string ProduktyUboczne {
            get {
                return ResourceManager.GetString("ProduktyUboczne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaje transportu.
        /// </summary>
        public static string RodzajeTransportu {
            get {
                return ResourceManager.GetString("RodzajeTransportu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj transportu.
        /// </summary>
        public static string RodzajTransportu {
            get {
                return ResourceManager.GetString("RodzajTransportu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Składniki zlecenia.
        /// </summary>
        public static string SkladnikiZlecenia {
            get {
                return ResourceManager.GetString("SkladnikiZlecenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Składnik zlecenia.
        /// </summary>
        public static string SkladnikZlecenia {
            get {
                return ResourceManager.GetString("SkladnikZlecenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sposób dostawy.
        /// </summary>
        public static string SposobDostawy {
            get {
                return ResourceManager.GetString("SposobDostawy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sposób płatności.
        /// </summary>
        public static string SposobPlatnosci {
            get {
                return ResourceManager.GetString("SposobPlatnosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sposoby dostawy.
        /// </summary>
        public static string SposobyDostawy {
            get {
                return ResourceManager.GetString("SposobyDostawy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sposoby płatności.
        /// </summary>
        public static string SposobyPlatnosci {
            get {
                return ResourceManager.GetString("SposobyPlatnosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły.
        /// </summary>
        public static string Szczegoly {
            get {
                return ResourceManager.GetString("Szczegoly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ ceny.
        /// </summary>
        public static string TypCeny {
            get {
                return ResourceManager.GetString("TypCeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ produktu.
        /// </summary>
        public static string TypProduktu {
            get {
                return ResourceManager.GetString("TypProduktu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ transakcji.
        /// </summary>
        public static string TypTransakcji {
            get {
                return ResourceManager.GetString("TypTransakcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typy cen.
        /// </summary>
        public static string TypyCen {
            get {
                return ResourceManager.GetString("TypyCen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typy produktów.
        /// </summary>
        public static string TypyProduktow {
            get {
                return ResourceManager.GetString("TypyProduktow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typy transakcji.
        /// </summary>
        public static string TypyTransakcji {
            get {
                return ResourceManager.GetString("TypyTransakcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Usun {
            get {
                return ResourceManager.GetString("Usun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwanie.
        /// </summary>
        public static string Usuwanie {
            get {
                return ResourceManager.GetString("Usuwanie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Zapisz {
            get {
                return ResourceManager.GetString("Zapisz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlecenia kompletacji.
        /// </summary>
        public static string ZleceniaKompletacji {
            get {
                return ResourceManager.GetString("ZleceniaKompletacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlecenia zakupu.
        /// </summary>
        public static string ZleceniaZakupu {
            get {
                return ResourceManager.GetString("ZleceniaZakupu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlecenie kompletacji.
        /// </summary>
        public static string ZlecenieKompletacji {
            get {
                return ResourceManager.GetString("ZlecenieKompletacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zlecenie zakupu.
        /// </summary>
        public static string ZlecenieZakupu {
            get {
                return ResourceManager.GetString("ZlecenieZakupu", resourceCulture);
            }
        }
    }
}
